# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SITHome_HabForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 580)
        Dialog.setMinimumSize(QtCore.QSize(850, 580))
        Dialog.setMaximumSize(QtCore.QSize(850, 550))
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, stop:0.386364 rgba(162, 254, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.493, y1:0, x2:0.502, y2:1, stop:0 rgba(0, 166, 255, 255), stop:1 rgba(162, 254, 255, 0));\n"
"border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 66))
        self.frame_2.setStyleSheet("background: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nombreHab = QtWidgets.QLabel(self.frame_2)
        self.nombreHab.setObjectName("nombreHab")
        self.verticalLayout_2.addWidget(self.nombreHab)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.nameRegister = QtWidgets.QLineEdit(self.frame_4)
        self.nameRegister.setGeometry(QtCore.QRect(90, 60, 251, 31))
        self.nameRegister.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nameRegister.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border : none;\n"
"font: 12pt;")
        self.nameRegister.setText("")
        self.nameRegister.setAlignment(QtCore.Qt.AlignCenter)
        self.nameRegister.setObjectName("nameRegister")
        self.btn_crear = QtWidgets.QPushButton(self.frame_4)
        self.btn_crear.setGeometry(QtCore.QRect(150, 140, 80, 35))
        self.btn_crear.setMinimumSize(QtCore.QSize(80, 35))
        self.btn_crear.setMaximumSize(QtCore.QSize(80, 35))
        self.btn_crear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_crear.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 15px;\n"
"font: 10pt;")
        self.btn_crear.setObjectName("btn_crear")
        self.btn_cancelar = QtWidgets.QPushButton(self.frame_4)
        self.btn_cancelar.setGeometry(QtCore.QRect(250, 140, 80, 35))
        self.btn_cancelar.setMinimumSize(QtCore.QSize(80, 35))
        self.btn_cancelar.setMaximumSize(QtCore.QSize(80, 35))
        self.btn_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar.setStyleSheet("background-color: white;\n"
"border-radius: 15px;\n"
"font: 10pt;")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.btn_guardar = QtWidgets.QPushButton(self.frame_4)
        self.btn_guardar.setGeometry(QtCore.QRect(50, 140, 80, 35))
        self.btn_guardar.setMinimumSize(QtCore.QSize(80, 35))
        self.btn_guardar.setMaximumSize(QtCore.QSize(80, 35))
        self.btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_guardar.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 15px;\n"
"font: 10pt;")
        self.btn_guardar.setObjectName("btn_guardar")
        self.hab_Exit = QtWidgets.QLabel(self.frame_4)
        self.hab_Exit.setEnabled(True)
        self.hab_Exit.setGeometry(QtCore.QRect(30, 100, 321, 31))
        self.hab_Exit.setStyleSheet("background-color: none;\n"
"color: white;")
        self.hab_Exit.setObjectName("hab_Exit")
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 421, 411))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SITHome-Formulario Habitación"))
        self.nombreHab.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#ffffff;\">Agregar o editar Habitación</span></p></body></html>"))
        self.nameRegister.setPlaceholderText(_translate("Dialog", "\"Sala principal\""))
        self.btn_crear.setText(_translate("Dialog", "Crear"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Nombre:</span></p></body></html>"))
        self.btn_guardar.setText(_translate("Dialog", "Guardar"))
        self.hab_Exit.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">El Nombre de la Habitación ya Existe</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Usuarios"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Permitido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
