# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\cosas\SITHome\interfaces\SITHome_HabForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 580)
        Dialog.setMinimumSize(QtCore.QSize(850, 580))
        Dialog.setMaximumSize(QtCore.QSize(850, 550))
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, stop:0.386364 rgba(162, 254, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.493, y1:0, x2:0.502, y2:1, stop:0 rgba(0, 166, 255, 255), stop:1 rgba(162, 254, 255, 0));\n"
"border-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 66))
        self.frame_2.setStyleSheet("background: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nombreHab = QtWidgets.QLabel(self.frame_2)
        self.nombreHab.setObjectName("nombreHab")
        self.verticalLayout_2.addWidget(self.nombreHab)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.nameRegister = QtWidgets.QLineEdit(self.frame_4)
        self.nameRegister.setGeometry(QtCore.QRect(90, 60, 251, 31))
        self.nameRegister.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nameRegister.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border : none;\n"
"font: 12pt;")
        self.nameRegister.setText("")
        self.nameRegister.setAlignment(QtCore.Qt.AlignCenter)
        self.nameRegister.setObjectName("nameRegister")
        self.btn_ok = QtWidgets.QPushButton(self.frame_4)
        self.btn_ok.setGeometry(QtCore.QRect(260, 140, 80, 35))
        self.btn_ok.setMinimumSize(QtCore.QSize(80, 35))
        self.btn_ok.setMaximumSize(QtCore.QSize(80, 35))
        self.btn_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ok.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 15px;\n"
"font: 10pt;")
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancelar = QtWidgets.QPushButton(self.frame_4)
        self.btn_cancelar.setGeometry(QtCore.QRect(170, 140, 80, 35))
        self.btn_cancelar.setMinimumSize(QtCore.QSize(80, 35))
        self.btn_cancelar.setMaximumSize(QtCore.QSize(80, 35))
        self.btn_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar.setStyleSheet("background-color: white;\n"
"border-radius: 15px;\n"
"font: 10pt;")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 421, 411))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nombreHab.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#ffffff;\">Agregar o editar Habitación</span></p></body></html>"))
        self.nameRegister.setPlaceholderText(_translate("Dialog", "\"Sala principal\""))
        self.btn_ok.setText(_translate("Dialog", "OK"))
        self.btn_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Nombre:</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Usuarios"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Permitido"))
